server:
  port: 7080

spring:
  application:
    name: servicio-productos
  datasource:
    dbcp2:
      driver-class-name: com.muysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tienda?serverTimezone=UTC
    username: curso
    password: curso
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
